version: "3.9"

services:
  api:
    container_name: api-prod
    build:
      context: ../..
      dockerfile: infra/docker/api.Dockerfile
    image: derivalia:prod
    env_file:
      - ../env/prod.env
    ports:
      - "3000:3000"
    restart: unless-stopped
